CREATE OR REPLACE TABLE PEOPLE USING TEMPLATE (
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE (INFER_SCHEMA(
    LOCATION=>'@AWS_EXT_STAGE_INTEGRATION/output_file.csv',
    FILE_FORMAT=>'CSV_INFER_FF'
    )));
